version: '3.8'
services:
  mssql:
    build:
      context: .
      dockerfile: Dockerfile.mssql
    container_name: mssql_test
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P YourStrong!Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init_db.sql:/init_db.sql:ro
      - ./init-db.sh:/init-db.sh:ro
  mssql_replica:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_replica
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1434:1433"
    restart: unless-stopped
    volumes:
      - mssql_replica_data:/var/opt/mssql
  
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mssql
    depends_on:
      - mssql
      - mssql_replica

volumes:
  mssql_data:
  mssql_replica_data:
